### ISSUE TITLE
Доработки к проекту.

### ISSUE THREAD

**Issue by liza-rd-brain** [liza-rd-brain/resume#1]
1. Вынести миксины для шрифтов.
2. Попоробвать поправить PP
3. Переработать передачу доп класса компоненту в параметр миксинаю
4.  Вестрать в адаптив.
5. В циклах указать не конечную цифру, а переменную (длинна массива).

**Comment by MinakovaLisa** [comment]
1. Не понимаю, может  и не стоит делать глобальные миксины шрифтам.

**Comment by liza-rd-brain** [comment]
5.-done
